//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxc.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int ID_Inventory { get; set; }
        public Nullable<int> ID_warehouse { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
    }
}
