//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxc.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class klient_Order
    {
        public int ID_Order { get; set; }
        public Nullable<int> ID_Klient { get; set; }
        public Nullable<int> ID_material { get; set; }
        public Nullable<double> total_Cost { get; set; }
        public Nullable<System.DateTime> Date_of_order { get; set; }
        public Nullable<System.DateTime> date_of_arrival { get; set; }
        public string status { get; set; }
        public Nullable<int> Warehouse { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
