//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxc.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logistika
    {
        public int ID_movement { get; set; }
        public Nullable<int> ID_Material { get; set; }
        public Nullable<int> ID_warehouse { get; set; }
        public Nullable<int> ID_site { get; set; }
        public Nullable<int> date_movement { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual construction_site construction_site { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
