//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxc.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Строй_Компания_И_закупка_материаловEntities : DbContext
    {
        public Строй_Компания_И_закупка_материаловEntities()
            : base("name=Строй_Компания_И_закупка_материаловEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<construction_site> construction_site { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<klient_Order> klient_Order { get; set; }
        public virtual DbSet<Logistika> Logistika { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<Supply_order> Supply_order { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
