//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zxc.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_order
    {
        public int ID_supply { get; set; }
        public Nullable<int> ID_Provider { get; set; }
        public Nullable<int> ID_material { get; set; }
        public Nullable<double> total_cost { get; set; }
        public Nullable<System.DateTime> Date_order { get; set; }
        public Nullable<System.DateTime> Date_arrival { get; set; }
        public string Status { get; set; }
        public Nullable<int> Warehouse { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
